### ISSUE TITLE
Adding Own Dataset Leads to a SANBertNetwork class Error

### ISSUE THREAD

**Issue by rudra0713** [UKPLab/mdl-stance-robustness#4]
Hi, I have followed the steps to add my own dataset for stance detection, but when I ran the code, it ran into an error:
```
Traceback (most recent call last):
  File "../train.py", line 477, in <module>
    main()
  File "../train.py", line 397, in main
    model.update(batch_meta, batch_data)
  File "/scratch/rrs99/mdl-stance-robustness/mt_dnn/model.py", line 123, in update
    logits = self.mnetwork(*inputs)
  File "/scratch/rrs99/venv/just_spacy/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch/rrs99/venv/just_spacy/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/scratch/rrs99/venv/just_spacy/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch/rrs99/mdl-stance-robustness/mt_dnn/matcher.py", line 107, in forward
    max_query = hyp_mask.size(1)
AttributeError: 'NoneType' object has no attribute 'size'

```
I have set the SAN_META variable for my dataset to be 1, although I am not quite sure what should be the value here. But this, in turn, set `decoder_opt` to 1 and it fails inside the forward function of `SANBertNetwork` class inside `matcher.py`. Can you kindly help me resolve this? Any help would be greatly appreiciated.

**Comment by v1nc3nt27** [comment]
Hi @rudra0713. How many inputs does you dataset have? SAN only works if it has two inputs (e.g. topic and sentence or sentence and sentence).

**Comment by rudra0713** [comment]
Hi, Thanks for your reply. My dataset has 2 inputs, claim and article. Initially, I set the DATA_TYPE for my dataset to be 1. But after doing some debugging, I thought, it needed to be set to 0, not 1. I did that, and then the issue was resolved.  

Was that the correct thing to do?

**Comment by v1nc3nt27** [comment]
Yap, DATA_TYPE set to 0 is correct for two inputs. However, you should also set SAN_META to 1, otherwise it won't use the SAN and I experienced a drop of some points if it is not used. You can read about what SAN does at https://www.aclweb.org/anthology/P19-1441, Section 3, "Pairwise Text Classification Output".
